package dev.quartermaster.android

import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue

internal object SmokeTag {
    const val OnboardingScreen = "smoke-onboarding-screen"
    const val InventoryScreen = "smoke-inventory-screen"
    const val ProductsScreen = "smoke-products-screen"
    const val ReminderScreen = "smoke-reminder-screen"
    const val SettingsScreen = "smoke-settings-screen"
    const val ServerUrlField = "smoke-server-url-field"
    const val UsernameField = "smoke-username-field"
    const val PasswordField = "smoke-password-field"
    const val SignInButton = "smoke-sign-in-button"
    const val RemindersTab = "smoke-tab-reminders"
    const val ProductsTab = "smoke-tab-products"
    const val SettingsTab = "smoke-tab-settings"
    const val ProductList = "smoke-product-list"
    const val ProductSearchField = "smoke-product-search-field"
    const val ProductSearchButton = "smoke-product-search-button"
    const val ProductFilterActive = "smoke-product-filter-active"
    const val ProductFilterAll = "smoke-product-filter-all"
    const val ProductFilterDeleted = "smoke-product-filter-deleted"
    const val ProductBarcodeField = "smoke-product-barcode-field"
    const val ProductBarcodeButton = "smoke-product-barcode-button"
    const val ProductCreateButton = "smoke-product-create-button"
    const val ProductNameField = "smoke-product-name-field"
    const val ProductBrandField = "smoke-product-brand-field"
    const val ProductImageUrlField = "smoke-product-image-url-field"
    const val ProductSubmitButton = "smoke-product-submit-button"
    const val ProductEditButton = "smoke-product-edit-button"
    const val ProductDeleteButton = "smoke-product-delete-button"
    const val ProductDeleteConfirmButton = "smoke-product-delete-confirm-button"
    const val ProductRestoreButton = "smoke-product-restore-button"
    const val ProductRefreshButton = "smoke-product-refresh-button"
    const val ReminderOpenedBanner = "smoke-reminder-opened-banner"
    const val ReminderOpenedDismissButton = "smoke-reminder-opened-dismiss"
    const val InviteHandoffCard = "smoke-invite-handoff-card"
    const val SwitchHouseholdHeader = "smoke-switch-household-header"
    const val SignOutButton = "smoke-sign-out-button"
    const val CreateInviteButton = "smoke-create-invite-button"
    const val LocationList = "smoke-location-list"
    const val LocationCreateButton = "smoke-location-create-button"
    const val LocationNameField = "smoke-location-name-field"
    const val LocationKindPantry = "smoke-location-kind-pantry"
    const val LocationKindFridge = "smoke-location-kind-fridge"
    const val LocationKindFreezer = "smoke-location-kind-freezer"
    const val LocationSubmitButton = "smoke-location-submit-button"
    const val StockEditScreen = "smoke-stock-edit-screen"
    const val StockEditQuantity = "smoke-stock-edit-quantity"
    const val StockEditExpires = "smoke-stock-edit-expires"
    const val StockEditOpened = "smoke-stock-edit-opened"
    const val StockEditNote = "smoke-stock-edit-note"
    const val StockEditSave = "smoke-stock-edit-save"
    const val StockEditCancel = "smoke-stock-edit-cancel"

    fun inventoryBatch(id: String) = "smoke-inventory-batch-$id"
    fun selectedBatch(id: String) = "smoke-selected-batch-$id"
    fun batchEditButton(id: String) = "smoke-batch-edit-$id"
    fun batchConsumeField(id: String) = "smoke-batch-consume-quantity-$id"
    fun batchConsumeButton(id: String) = "smoke-batch-consume-$id"
    fun batchDiscardButton(id: String) = "smoke-batch-discard-$id"
    fun batchRestoreButton(id: String) = "smoke-batch-restore-$id"
    fun batchHistoryRow(id: String) = "smoke-batch-history-$id"
    fun reminderCard(id: String) = "smoke-reminder-card-$id"
    fun reminderAckButton(id: String) = "smoke-reminder-ack-$id"
    fun reminderOpenButton(id: String) = "smoke-reminder-open-$id"
    fun inviteCode(code: String) = "smoke-invite-code-$code"
    fun reminderTarget(batchId: String) = "smoke-reminder-target-$batchId"
    fun productRow(id: String) = "smoke-product-row-$id"
    fun locationEdit(id: String) = "smoke-location-edit-$id"
    fun locationDelete(id: String) = "smoke-location-delete-$id"
    fun locationDeleteConfirm(id: String) = "smoke-location-delete-confirm-$id"
    fun locationMoveUp(id: String) = "smoke-location-move-up-$id"
    fun locationMoveDown(id: String) = "smoke-location-move-down-$id"
    fun stockEditLocation(id: String) = "smoke-stock-edit-location-$id"
}
